package olcrtc

// profileCoreConfig is what we store (as JSON) in models.Profile.CoreConfig
// for CoreOlcRTC profiles.
//
// RoomID cannot be generated by the panel: upstream's built-in providers
// (jitsi/telemost/wbstream) don't support room creation via olcrtc itself
// (docs/configuration.md, "mode: gen" section) — for telemost/wbstream the
// operator must create the room on the provider's site first and paste the
// id/URL here; for jitsi it's the meeting URL.
//
// CryptoKey is infra: generated once (or supplied by the operator) and kept
// stable across edits — regenerating it would break every client already
// using this profile. Vp8/Sei/Video only matter for their matching
// Transport and are hidden behind "advanced" in the UI — defaults come
// straight from docs/settings.md's "Рекомендуется" rows.
type profileCoreConfig struct {
	Provider  string `json:"provider"` // "jitsi", "telemost", "wbstream"
	RoomID    string `json:"room_id"`
	Transport string `json:"transport"`            // "datachannel", "vp8channel", "seichannel", "videochannel"
	CryptoKey string `json:"crypto_key,omitempty"` // 64 hex chars
	DNS       string `json:"dns,omitempty"`        // e.g. "1.1.1.1:53"
	// ProxyUpstream is an optional outbound SOCKS5 proxy for olcrtc's own
	// egress (docs/settings.md upstream, server-only "socks:" block) — same
	// "socks5://[user:pass@]host:port" shape and same reasoning as webdav's
	// own ProxyUpstream (provisioner/webdav/config.go): so the kernel's
	// traffic to the video-call provider goes through a tunnel/VPN instead
	// of the VPS's own IP directly. Stored here as one URL string (matching
	// the operator-facing field everywhere else in this panel); split into
	// olcrtc's own separate proxy_addr/proxy_port/proxy_user/proxy_pass
	// YAML keys only at writeYAML time — see parseSocksProxy.
	ProxyUpstream string `json:"proxy_upstream,omitempty"`

	// AuthToken is a pre-issued account token for provider "wbstream" only
	// (docs/settings.md upstream, "auth.token") — enables moderator
	// features (datachannel publishing) for that provider. Meaningless for
	// jitsi/telemost, so the UI only shows it when Provider == "wbstream".
	AuthToken string `json:"auth_token,omitempty"`

	// Liveness/MaxSessionDuration are optional advanced connection-health
	// knobs (docs/settings.md upstream, "liveness:"/"lifecycle:" blocks) —
	// same "empty means let olcrtc apply its own default" convention as
	// webdav's own tuning fields (provisioner/webdav/config.go): every
	// sub-field is only ever written to the YAML if the operator actually
	// set it, so an untouched field falls back to whatever olcrtc's own
	// built-in default for it is, not a value this panel silently pins.
	Liveness           *livenessConfig `json:"liveness,omitempty"`
	MaxSessionDuration string          `json:"max_session_duration,omitempty"` // e.g. "6h"; empty = disabled (never auto-rebuilds)

	Vp8   *vp8Config   `json:"vp8,omitempty"`
	Sei   *seiConfig   `json:"sei,omitempty"`
	Video *videoConfig `json:"video,omitempty"`
}

// livenessConfig tunes olcrtc's own control-stream heartbeat (upstream
// defaults: interval 10s, timeout 15s, failures 4) — lower values notice a
// dead link and rebuild sooner on flaky networks; higher values avoid
// rebuilding over a merely slow reply.
type livenessConfig struct {
	Interval string `json:"interval,omitempty"` // e.g. "10s"
	Timeout  string `json:"timeout,omitempty"`  // e.g. "15s"
	Failures int    `json:"failures,omitempty"` // consecutive misses before rebuild
}

type vp8Config struct {
	FPS       int `json:"fps,omitempty"`
	BatchSize int `json:"batch_size,omitempty"`
}

type seiConfig struct {
	FPS          int `json:"fps,omitempty"`
	BatchSize    int `json:"batch_size,omitempty"`
	FragmentSize int `json:"fragment_size,omitempty"`
	AckTimeoutMs int `json:"ack_timeout_ms,omitempty"`
}

type videoConfig struct {
	Codec      string `json:"codec,omitempty"` // "qrcode" or "tile"
	Width      int    `json:"width,omitempty"`
	Height     int    `json:"height,omitempty"`
	FPS        int    `json:"fps,omitempty"`
	QRRecovery string `json:"qr_recovery,omitempty"` // "low", "medium", "high", "highest"
	QRSize     int    `json:"qr_size,omitempty"`     // 0 = auto
	TileModule int    `json:"tile_module,omitempty"` // 1..270, "tile" codec only
	TileRS     int    `json:"tile_rs,omitempty"`     // 0..200 (%), "tile" codec only
}

// yamlConfig mirrors the olcrtc YAML schema (docs/configuration.md). Only
// the block matching profileCoreConfig.Transport is ever populated.
type yamlConfig struct {
	Mode string `yaml:"mode"`
	Auth struct {
		Provider string `yaml:"provider"`
		Token    string `yaml:"token,omitempty"`
	} `yaml:"auth"`
	Room struct {
		ID string `yaml:"id"`
	} `yaml:"room"`
	Crypto struct {
		Key string `yaml:"key"`
	} `yaml:"crypto"`
	Net struct {
		Transport string `yaml:"transport"`
		DNS       string `yaml:"dns"`
	} `yaml:"net"`
	Vp8       *vp8YAML       `yaml:"vp8,omitempty"`
	Sei       *seiYAML       `yaml:"sei,omitempty"`
	Video     *videoYAML     `yaml:"video,omitempty"`
	Socks     *socksYAML     `yaml:"socks,omitempty"`
	Liveness  *livenessYAML  `yaml:"liveness,omitempty"`
	Lifecycle *lifecycleYAML `yaml:"lifecycle,omitempty"`
}

type livenessYAML struct {
	Interval string `yaml:"interval,omitempty"`
	Timeout  string `yaml:"timeout,omitempty"`
	Failures int    `yaml:"failures,omitempty"`
}

type lifecycleYAML struct {
	MaxSessionDuration string `yaml:"max_session_duration,omitempty"`
}

// socksYAML is olcrtc's own "socks:" server-mode block (docs/settings.md
// upstream) — ProxyUser/ProxyPass are RFC 1929 SOCKS5 username/password
// auth, optional (upstream: "omit for no auth").
type socksYAML struct {
	ProxyAddr string `yaml:"proxy_addr,omitempty"`
	ProxyPort int    `yaml:"proxy_port,omitempty"`
	ProxyUser string `yaml:"proxy_user,omitempty"`
	ProxyPass string `yaml:"proxy_pass,omitempty"`
}

type vp8YAML struct {
	FPS       int `yaml:"fps"`
	BatchSize int `yaml:"batch_size"`
}

type seiYAML struct {
	FPS          int `yaml:"fps"`
	BatchSize    int `yaml:"batch_size"`
	FragmentSize int `yaml:"fragment_size"`
	AckTimeoutMs int `yaml:"ack_timeout_ms"`
}

type videoYAML struct {
	Codec      string `yaml:"codec"`
	Width      int    `yaml:"width"`
	Height     int    `yaml:"height"`
	FPS        int    `yaml:"fps"`
	QRRecovery string `yaml:"qr_recovery"`
	QRSize     int    `yaml:"qr_size"`
	TileModule int    `yaml:"tile_module,omitempty"`
	TileRS     int    `yaml:"tile_rs,omitempty"`
}
