package olcrtc

// profileCoreConfig is what we store (as JSON) in models.Profile.CoreConfig
// for CoreOlcRTC profiles.
//
// RoomID cannot be generated by the panel: upstream's built-in providers
// (jitsi/telemost/wbstream) don't support room creation via olcrtc itself
// (docs/configuration.md, "mode: gen" section) — for telemost/wbstream the
// operator must create the room on the provider's site first and paste the
// id/URL here; for jitsi it's the meeting URL.
//
// CryptoKey is infra: generated once (or supplied by the operator) and kept
// stable across edits — regenerating it would break every client already
// using this profile. Vp8/Sei/Video only matter for their matching
// Transport and are hidden behind "advanced" in the UI — defaults come
// straight from docs/settings.md's "Рекомендуется" rows.
type profileCoreConfig struct {
	Provider  string `json:"provider"` // "jitsi", "telemost", "wbstream"
	RoomID    string `json:"room_id"`
	Transport string `json:"transport"`             // "datachannel", "vp8channel", "seichannel", "videochannel"
	CryptoKey string `json:"crypto_key,omitempty"`   // 64 hex chars
	DNS       string `json:"dns,omitempty"`          // e.g. "1.1.1.1:53"

	Vp8   *vp8Config   `json:"vp8,omitempty"`
	Sei   *seiConfig   `json:"sei,omitempty"`
	Video *videoConfig `json:"video,omitempty"`
}

type vp8Config struct {
	FPS       int `json:"fps,omitempty"`
	BatchSize int `json:"batch_size,omitempty"`
}

type seiConfig struct {
	FPS          int `json:"fps,omitempty"`
	BatchSize    int `json:"batch_size,omitempty"`
	FragmentSize int `json:"fragment_size,omitempty"`
	AckTimeoutMs int `json:"ack_timeout_ms,omitempty"`
}

type videoConfig struct {
	Codec      string `json:"codec,omitempty"`       // "qrcode" or "tile"
	Width      int    `json:"width,omitempty"`
	Height     int    `json:"height,omitempty"`
	FPS        int    `json:"fps,omitempty"`
	QRRecovery string `json:"qr_recovery,omitempty"`  // "low", "medium", "high", "highest"
	QRSize     int    `json:"qr_size,omitempty"`      // 0 = auto
	TileModule int    `json:"tile_module,omitempty"`  // 1..270, "tile" codec only
	TileRS     int    `json:"tile_rs,omitempty"`      // 0..200 (%), "tile" codec only
}

// yamlConfig mirrors the olcrtc YAML schema (docs/configuration.md). Only
// the block matching profileCoreConfig.Transport is ever populated.
type yamlConfig struct {
	Mode string `yaml:"mode"`
	Auth struct {
		Provider string `yaml:"provider"`
	} `yaml:"auth"`
	Room struct {
		ID string `yaml:"id"`
	} `yaml:"room"`
	Crypto struct {
		Key string `yaml:"key"`
	} `yaml:"crypto"`
	Net struct {
		Transport string `yaml:"transport"`
		DNS       string `yaml:"dns"`
	} `yaml:"net"`
	Vp8   *vp8YAML   `yaml:"vp8,omitempty"`
	Sei   *seiYAML   `yaml:"sei,omitempty"`
	Video *videoYAML `yaml:"video,omitempty"`
}

type vp8YAML struct {
	FPS       int `yaml:"fps"`
	BatchSize int `yaml:"batch_size"`
}

type seiYAML struct {
	FPS          int `yaml:"fps"`
	BatchSize    int `yaml:"batch_size"`
	FragmentSize int `yaml:"fragment_size"`
	AckTimeoutMs int `yaml:"ack_timeout_ms"`
}

type videoYAML struct {
	Codec      string `yaml:"codec"`
	Width      int    `yaml:"width"`
	Height     int    `yaml:"height"`
	FPS        int    `yaml:"fps"`
	QRRecovery string `yaml:"qr_recovery"`
	QRSize     int    `yaml:"qr_size"`
	TileModule int    `yaml:"tile_module,omitempty"`
	TileRS     int    `yaml:"tile_rs,omitempty"`
}
