package turnable

// serverFile mirrors Turnable's server config.json (docs/server/CONFIG.md).
// One is rendered per profile — its own process, port, call_id, with
// exactly one route + one user embedded (the "raw" provider) — so editing one never touches another's process.
type serverFile struct {
	Servers   map[string]serverEntry   `json:"servers"`
	Providers map[string]providerEntry `json:"providers"`
}

type serverEntry struct {
	Type       string `json:"type"` // always "relay" — the only value Turnable's server itself supports
	PlatformID string `json:"platform_id"`
	CallID     string `json:"call_id"`
	PubKey     string `json:"pub_key"`
	PrivKey    string `json:"priv_key"`
	Proto      string `json:"proto,omitempty"`
	ListenAddr string `json:"listen_addr"`
	PublicIP   string `json:"public_ip"`
	Cloak      string `json:"cloak,omitempty"`
	Provider   string `json:"provider"`
}

type providerEntry struct {
	Type   string  `json:"type"`
	Routes []route `json:"routes,omitempty"`
	Users  []user  `json:"users,omitempty"`
}

type route struct {
	ID         string `json:"id"`
	Address    string `json:"address"`
	Port       int    `json:"port"`
	Socket     string `json:"socket"`
	Transport  string `json:"transport,omitempty"`
	Encryption string `json:"encryption,omitempty"`
	Name       string `json:"name,omitempty"`
}

type user struct {
	UUID          string   `json:"uuid"`
	AllowedRoutes []string `json:"allowed_routes"`
	Type          string   `json:"type"` // always "relay" here — "p2p" isn't implemented upstream yet
	Peers         int      `json:"peers"`
	// forceturn is deliberately not modeled: it only ever applied to the
	// unimplemented "p2p" user type and was dropped from "relay" users.
}

// profileCoreConfig is what we store (as JSON) in models.Profile.CoreConfig
// for CoreTurnable profiles.
//
// Port/PubKey/PrivKey are infra: minted once in AddProfile, never re-minted
// by UpdateProfile, since the client's turnable:// URI already bakes in the
// port as "gateway". PlatformID/RouteAddr/RouteSocket fall back to
// config.TurnableDefault* when left empty.
//
// ConnectionType is NOT the server config's "type" (always "relay") — it's
// the client-facing `type=` query param: "relay" (default) tunnels through
// our server, "direct" bypasses it (upstream flags this "dangerous to use").
//
// CallID cannot be generated by the panel — the operator must create the
// call/meeting on the platform first; each profile needs a distinct call
// since it's its own Turnable process.
type profileCoreConfig struct {
	ConnectionType string `json:"connection_type,omitempty"` // "relay" (default) or "direct"
	CallID         string `json:"call_id"`
	Peers          int    `json:"peers"`
	PlatformID     string `json:"platform_id,omitempty"`
	Proto          string `json:"proto,omitempty"`      // "srtp" (default/recommended), "dtls", or "none" (dangerous)
	Encryption     string `json:"encryption,omitempty"` // "handshake" (default) or "full" — see upstream REFERENCE.md "Encryption Modes"

	RouteAddr      string `json:"route_addr,omitempty"`      // host only, e.g. "127.0.0.1"
	RoutePort      int    `json:"route_port,omitempty"`      // required, no default
	RouteSocket    string `json:"route_socket,omitempty"`    // "udp" or "tcp"
	RouteTransport string `json:"route_transport,omitempty"` // "none" or "kcp"

	Port    int    `json:"port"`
	PubKey  string `json:"pub_key"`
	PrivKey string `json:"priv_key"`
}
