package turnable

// serverFile mirrors the top-level structure of Turnable's server config.json
// (docs/server/CONFIG.md upstream). One of these is rendered per profile:
// each profile is its own Turnable server process, own listen port, own
// call_id, with exactly one route + one user embedded directly (the "raw"
// provider), so editing or removing one profile never touches another's
// running process.
type serverFile struct {
	Servers   map[string]serverEntry   `json:"servers"`
	Providers map[string]providerEntry `json:"providers"`
}

type serverEntry struct {
	Type       string `json:"type"` // always "relay" — the only value Turnable's server itself supports
	PlatformID string `json:"platform_id"`
	CallID     string `json:"call_id"`
	PubKey     string `json:"pub_key"`
	PrivKey    string `json:"priv_key"`
	Proto      string `json:"proto,omitempty"`
	ListenAddr string `json:"listen_addr"`
	PublicIP   string `json:"public_ip"`
	Cloak      string `json:"cloak,omitempty"`
	Provider   string `json:"provider"`
}

type providerEntry struct {
	Type   string  `json:"type"`
	Routes []route `json:"routes,omitempty"`
	Users  []user  `json:"users,omitempty"`
}

type route struct {
	ID         string `json:"id"`
	Address    string `json:"address"`
	Port       int    `json:"port"`
	Socket     string `json:"socket"`
	Transport  string `json:"transport,omitempty"`
	Encryption string `json:"encryption,omitempty"`
	Name       string `json:"name,omitempty"`
}

type user struct {
	UUID          string   `json:"uuid"`
	AllowedRoutes []string `json:"allowed_routes"`
	Type          string   `json:"type"` // always "relay" here — "p2p" isn't implemented upstream yet
	Peers         int      `json:"peers"`
	// forceturn is deliberately not modeled: it only ever applied to the
	// unimplemented "p2p" user type and was dropped from "relay" users.
}

// profileCoreConfig is what we store (as JSON) in models.Profile.CoreConfig
// for CoreTurnable profiles.
//
// Infra fields — Port, PubKey, PrivKey — are assigned once in AddProfile
// and never re-minted by UpdateProfile: the client's turnable:// URI
// already has the port baked in as "gateway", and there's no reason to
// rotate a working profile's key material on an unrelated edit.
//
// Logical fields can be edited; PlatformID/RouteAddr/RouteSocket fall back
// to the panel-wide config.Config defaults when left empty (see
// config.TurnableDefault*), but any profile can override them.
//
// ConnectionType is NOT the server config's "type" field (always "relay" —
// the only mode Turnable's server itself implements) — it's the `type=`
// query parameter in the client-facing turnable:// URI, telling the
// WireTurn client whether to tunnel through our server ("relay", default)
// or attempt to bypass it entirely ("direct" — upstream flags this
// "dangerous to use").
//
// CallID cannot be generated by the panel — same constraint as olcRTC's
// room_id: the operator must create the underlying platform call/meeting
// first and paste its id here. Because every profile is its own Turnable
// process, isolation on the TURN/SFU platform requires each profile to use
// a distinct call — reusing one call_id across processes is not assumed
// safe.
type profileCoreConfig struct {
	ConnectionType string `json:"connection_type,omitempty"` // "relay" (default) or "direct"
	CallID         string `json:"call_id"`
	Peers          int    `json:"peers"`
	PlatformID     string `json:"platform_id,omitempty"`
	Proto          string `json:"proto,omitempty"`      // "srtp" (default/recommended), "dtls", or "none" (dangerous)
	Encryption     string `json:"encryption,omitempty"` // "handshake" (default) or "full" — see upstream REFERENCE.md "Encryption Modes"

	RouteAddr      string `json:"route_addr,omitempty"`      // host only, e.g. "127.0.0.1"
	RoutePort      int    `json:"route_port,omitempty"`      // required, no default
	RouteSocket    string `json:"route_socket,omitempty"`    // "udp" or "tcp"
	RouteTransport string `json:"route_transport,omitempty"` // "none" or "kcp"

	Port    int    `json:"port"`
	PubKey  string `json:"pub_key"`
	PrivKey string `json:"priv_key"`
}
